### PR TITLE
Module modernisation

### LINKED ISSUE #101: Please update local provider requirement to 2.0.0 version
Have a question? Please checkout our [Slack Community](https://slack.cloudposse.com) or visit our [Slack Archive](https://archive.sweetops.com/). 

[Slack Community](https://slack.cloudposse.com)

## Describe the Feature

Please update local provider requirement to 2.0.0 version

## Expected Behavior

Possibility to pass latest provider via providers block.

## Use Case

Having a single top level provider definition

### PR DESCRIPTION
**Pull request by joe-niland**
## what
* relax provider pinning
* add chatops
* add autorelease
* use new terratest structure

## why
* Allow this module to be consumed by modules using later version of providers
* Add gitops automation

## references
* closes #101

### CODE REVIEW

**Review by aknysh — COMMENTED** [review]
thanks @joe-niland, LGTM
Can you please update this as well https://github.com/joe-niland/terraform-aws-ecs-container-definition/blob/update-provider-pinning/examples/complete/versions.tf

Also, we are updating all out modules to `context.tf`, would be nice to do it in this PR instead of opening another one later.
We are basically adding `context.tf` files to the module and to the example (and removing some variables that are already present in `context.tf`).
Here is how to do it:

https://github.com/cloudposse/terraform-aws-service-control-policies/blob/master/context.tf

https://github.com/cloudposse/terraform-aws-service-control-policies/blob/master/examples/complete/main.tf#L7

https://github.com/cloudposse/terraform-aws-service-control-policies/blob/master/examples/complete/context.tf

thank you

**Comment by joe-niland** [comment]
Hi @aknysh 

I'll fix the example - missed that!

Regarding context, I did look at that but I ended up removing it because:
- the `environment` variable conflicts
- there is no label module usage

Let me know if I should add. I can at least change `var.environment` to use `module.this.environment`

**Comment by aknysh** [comment]
> Hi @aknysh
> 
> I'll fix the example - missed that!
> 
> Regarding context, I did look at that but I ended up removing it because:
> 
> * the `environment` variable conflicts
> * there is no label module usage
> 
> Let me know if I should add. I can at least change `var.environment` to use `module.this.environment`

ah yes, this module is just a converter, no need for `context.tf`

**Review by aknysh — APPROVED** [review]

**Pull request merged**
