### PR TITLE
fix: log config

### PR DESCRIPTION
**Pull request by ArchiFleKs**
Fix this error:

```
Error: Invalid function argument                                                                                                                                                                                                         
                                                                                                                                                                                                                                         
  on main.tf line 32, in locals:                                                                                                                                                                                                         
  32:   log_configuration_secret_options = var.log_configuration != null ? lookup(var.log_configuration, "secretOptions", null) : null                                                                                                   
    |----------------                                                                                                                                                                                                                        | var.log_configuration is "{\"logDriver\":\"json-file\",\"options\":{\"max-file\":\"3\",\"max-size\":\"10m\"},\"secretOptions\":null}"                                                                                                                                                                                                                                                                                                                                       
Invalid value for "inputMap" parameter: lookup() requires a map as the first                                                                                                                                                             argument.                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
Releasing state lock. This may take a few moments...                                                                                                                                                                                     
[terragrunt] 2020/08/04 10:29:47 Hit multiple errors:          
```

### CODE REVIEW

**Comment by nitrocode** [comment]
@archifleks can you share your input for that variable?

**Comment by ArchiFleKs** [comment]
@nitrocode: 

```
log_configuration = {
    logDriver = "awslogs"
    options = {
      "awslogs-create-group"  = true
      "awslogs-region"        = "eu-central-1"
      "awslogs-group"         = "mysqldump"
      "awslogs-stream-prefix" = "cfd-dev"
    }
    secretOptions = null
```

**Comment by nitrocode** [comment]
Thank you.

Have you tested this change locally to make sure this works too?

**Pull request merged**
