### PR TITLE
Add support for systemControls

### PR DESCRIPTION
**Pull request by lisajluo**

### CODE REVIEW

**Comment by aknysh** [comment]
@lisajluo 
please rebase
also lease rebuild README by executing these commands:

```
make init
make readme/deps
make readme
```

It will add the new variables and outputs to `README.md` automatically.

In general, any changes to README should be made in `README.yaml` (not in this case), and after that executing the commands above will rebuild `README.yaml` into `README.md` and add all new variables and outputs to `README.md`

thanks

**Comment by lisajluo** [comment]
@aknysh Sure, updated. It doesn't seem to have pulled in anything for this PR though. 🤷‍♀

**Comment by aknysh** [comment]
can you make sure you rebased the branch and then execute again

```
make init
make readme/deps
make readme
```

**Comment by lisajluo** [comment]
My bad. Fixed.

**Pull request merged**
