### PR TITLE
Cleaner multiple definition example using json_map

### PR DESCRIPTION
**Pull request by nitrocode**
## what
* Cleaner multiple definition example using json_map

## why
* Best practices and readability

## references
N/A

### CODE REVIEW

**Review by Gowiem — APPROVED** [review]

**Comment by Gowiem** [comment]
@nitrocode if validate-codeowners doesn't complete then you might need to push an empty commit: 

```bash
git commit --allow-empty -m "feat: trigger CI"
```

**Comment by nitrocode** [comment]
I think I messed it up...

**Review by Gowiem — APPROVED** [review]

**Review by CaseyLabs — COMMENTED** [review]
Is this a typo, should:
`module.first_container.json_map,`

be

`module.first_container.json_map_encoded,`

?

**Comment by nitrocode** [comment]
Is something broken ?

**Comment by CaseyLabs** [comment]
That's what I'm trying to figure out at the moment. This block:

```resource "aws_ecs_task_definition" "main" {
  family = local.unique_name
  container_definitions = jsonencode([
    module.first_container.json_map,
    module.second_container.json_map
  ])
}```

Results in `This object does not have an attribute named "json_map"` for both objects.

This works however:

```resource "aws_ecs_task_definition" "main" {
  family = local.unique_name
  container_definitions = jsonencode([
    module.service_container_definition.json_map_encoded,
    module.monitoring_container_definition.json_map_encoded
  ])
}```

I'm on my first coffee this morning, so may be missing something on my side ;-)

**Comment by nitrocode** [comment]
Ah you're right. Thank you. https://github.com/cloudposse/terraform-aws-ecs-container-definition/pull/132

**Pull request merged**
