### PR TITLE
Add resourceRequirements key 

### LINKED ISSUE #105: Missing Keys: ResourceRequirement
Missing resource: `ResourceRequirement`

https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ResourceRequirement.html

This one is used in tandem with interface accelerators

### PR DESCRIPTION
**Pull request by karvounis**
## what
* The key `resourceRequirements` is added based on https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html
* Very simple addition of one variable that is a list of `ResourceRequirement` objects https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ResourceRequirement.html

## why
* The key `resourceRequirements` was missing and I was not able to add a GPU requirement to the container definition

## references
* https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html
* https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ResourceRequirement.html
* https://github.com/cloudposse/terraform-aws-ecs-container-definition/issues/105
* `closes #105`

### CODE REVIEW

**Comment by karvounis** [comment]
hmmmm why is test/bats failing? how can I fix that?

**Comment by joe-niland** [comment]
@karvounis in `versions.tf` change the module pinning to use the format shown here: https://www.terraform.io/docs/modules/sources.html#terraform-registry

E.g.

```
module "consul" {
  source = "hashicorp/consul/aws"
  version = "0.1.0"
}
```

**Comment by karvounis** [comment]
Sorry @joe-niland I do not understand why module pinning is going to work and pass the tests. The repo is not using any modules at all just the `local` provider. 
https://github.com/cloudposse/terraform-aws-ec2-instance-group/blob/master/versions.tf
https://github.com/cloudposse/terraform-aws-vpn-connection/blob/master/versions.tf
The above 2 repos do not have module pinning and they still pass the tests.

This is my first contribution to a cloudposse repo and I do not know the drill :)

**Comment by joe-niland** [comment]
@karvounis sorry for the confusing response. When I wrote module I meant provider.

It needs to be done in the same way as the VPN module. The other one would not pass if a new PR was opened.

If you change `versions.tf`to that style, the bats test should pass.

**Review by maximmi — APPROVED** [review]

**Pull request merged**
