### PR TITLE
Make log_configuration's secretOptions optional

### PR DESCRIPTION
**Pull request by nitrocode**
Fixes https://github.com/cloudposse/terraform-aws-ecs-container-definition/issues/75 by setting a default value for `secretOptions` as shown in [this comment](https://github.com/hashicorp/terraform/issues/19898#issuecomment-517366924).

@aknysh @osterman review please

### CODE REVIEW

**Comment by nitrocode** [comment]
@osterman not sure why but the readme update action deleted all the inputs in the docs...

**Comment by osterman** [comment]
@nitrocode very wierd! haven't seen that one happen before.

**Comment by nitrocode** [comment]
https://github.com/cloudposse/build-harness/pull/218

**Comment by nitrocode** [comment]
@osterman looks like the major difference in the docs is the escaping of underscores using `\_`

**Comment by osterman** [comment]
@nitrocode this is the new version of `terraform-docs`

Previously we used an [atrocious hack](https://github.com/cloudposse/build-harness/blob/master/bin/terraform-docs.awk) because for the longest time `terraform-docs` did not support 0.12. The underscores are intentional, I believe, to ensure proper markdown formatting in all cases.

**Comment by osterman** [comment]
Additional context about the backslashes here: https://github.com/segmentio/terraform-docs/issues/111

**Comment by osterman** [comment]
Looks like we can add `--no-escape` to get rid of it. https://github.com/segmentio/terraform-docs/pull/117

**Comment by osterman** [comment]
I'm okay either way. Want to wait and PR the build-harness or fix conflicts and merge? =)

**Pull request merged**
