### PR TITLE
Add support for extraHosts option

### PR DESCRIPTION
**Pull request by michelmzs**
Add the variable `extra_hosts` to support extraHosts field.
Reference: https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_ContainerDefinition.html

### CODE REVIEW

**Comment by aknysh** [comment]
@michelmzs please rebase

**Comment by michelmzs** [comment]
Rebased @aknysh

**Comment by Gowiem** [comment]
@michelmzs Released as [v0.28.0](https://github.com/cloudposse/terraform-aws-ecs-container-definition/releases/tag/0.28.0). Thanks!

**Pull request merged**
