### PR TITLE
Fix typo in key of container definition

### PR DESCRIPTION
**Pull request by clifford-sanders**
## what
A key in the container definition had a typo. `preudoTerminal` instead of `pseudoTerminal`

## why
Because of this typo it was impossible to enable the pseudoTerminal (tty)

## references
n/a

### CODE REVIEW

**Comment by clifford-sanders** [comment]
Hi, I don't understand, what to do to solve the failed check.

What do I have to do?

**Review by Nuru — CHANGES_REQUESTED** [review]
Please wait. We will include this in #118 or merge it after.

**Review by Nuru — APPROVED** [review]

**Comment by clifford-sanders** [comment]
Thanks for the quick merge to master.

If I'm correct, the latest versions are not compatible to Terraform 0.12 anymore.
Will this fix be backported to the last version, that is compatible?

I currently use a branch of tag 0.43.0 for this.

**Pull request merged**
