### PR TITLE
feat: add map_secrets

### LINKED ISSUE #106: Improve interface of the "secrets" input variable
This is a suggestion, very similar to the one already created  in #61 and improvement is closed.

The current way of passing secrets variables to the module is by using a list of maps

```
variable "secrets" {
  type = list(object({
    name      = string
    valueFrom = string
  }))
  description = "The secrets to pass to the container. This is a list of maps"
  default     = null
}

```

eg. with using parameter store

```
secrets = [
    {
      name  = "SECRET_1",
      valueFrom = "arn:aws:ssm:region:aws_account_id:parameter/parameter1_name"
    },
    {
      name  = "SECRET_2",
      valueFrom = "arn:aws:ssm:region:aws_account_id:parameter/parameter2_name"
    }
  ]
```
Hardcoded part of ARN (region and aws_account_id) i guess can be managed dynamically with local variables.
Maybe there can be some refactoring to create `type = map(any)` variable
```
map_secrets = {
      "SECRET_1" = "parameter/parameter1_name"
      "SECRET_2" = "parameter/parameter2_name"
    }
```
Do you think this is possible?

Thanks,
Dejan

### PR DESCRIPTION
**Pull request by davidvasandani**
## what
* provides an improved input to the secrets variable

## why
* improves secrets input

## references
* closes #106

### CODE REVIEW

**Comment by Nuru** [comment]
@davidvasandani Please [allow maintainers to update this PR](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork#enabling-repository-maintainer-permissions-on-existing-pull-requests) so that we can update the README.

**Comment by nitrocode** [comment]
I'll leave this open until the other is closed

**Pull request closed without merging**
