### PR TITLE
Add read_only to mount_points and set default

### PR DESCRIPTION
**Pull request by nitrocode**
Fixes https://github.com/cloudposse/terraform-aws-ecs-container-definition/issues/66

@aknysh @osterman review please

There is a funky way way to add `readOnly` as an optional key so it won't have to be defined for every item in `mount_points`. I used a default of `false` unless otherwise defined. This technique also verifies the type of each key.

### CODE REVIEW

**Comment by Gowiem** [comment]
@nitrocode optional keys don't look to be supported -- There's an open feature request for that: https://github.com/hashicorp/terraform/issues/19898

**Comment by osterman** [comment]
@nitrocode @Gowiem see https://github.com/cloudposse/terraform-aws-ecs-container-definition/pull/65#issuecomment-635489454 can we use this?

**Pull request merged**
