### PR TITLE
Add map_environment variable

### PR DESCRIPTION
**Pull request by littlejo**
instead of using environment variable, I suggest to use map_environment variable

It's similar as request #61

### CODE REVIEW

**Comment by aknysh** [comment]
@littlejo please rebase

**Comment by littlejo** [comment]
> @littlejo please rebase

Done

**Comment by osterman** [comment]
Might #81 more generally address this?

**Comment by nitrocode** [comment]
I added the sorting logic to your fork @littlejo

**Comment by nitrocode** [comment]
@Gowiem I believe your changes requested have been fulfilled. Could you double check please?

**Comment by nitrocode** [comment]
@osterman @Gowiem had to resolve conflicts which caused another merge which invalidated prior approvals. Please take another look.

**Comment by Gowiem** [comment]
@littlejo Thanks for the contribution! Released as [0.36.0](https://github.com/cloudposse/terraform-aws-ecs-container-definition/releases/tag/0.36.0).

**Pull request merged**
