### PR TITLE
Fix: Duplicate name in portMapping fixed & Docs Updated

### PR DESCRIPTION
**Pull request by Hackerbone**
## what

The `portMapping` parameter had a duplicate `name` field occurrence

## why

Failure in creating services in the new release v0.61.0

## references

I was waiting for the previous PR to get merged since I use this module in my project for a while. Saw CI checks didn't pass so I made a new fix PR.

- closes #170

### CODE REVIEW

**Review by balajimoses — APPROVED** [review]

**Review by nitrocode — DISMISSED** [review]

**Comment by Hackerbone** [comment]
Hey @nitrocode can you re-approve workflow? I ran the make init/readme commands

**Review by nitrocode — APPROVED** [review]

**Comment by Hackerbone** [comment]
Hi @nitrocode, I think running only `/terratest` should work?

**Pull request merged**
