### PR TITLE
Feat: Add `skip_destroy` Variable

### PR DESCRIPTION
**Pull request by cunymatthieu**
## what
Adding a `skip_destroy` variable

## why
* Very useful for deploying a new version of the ECS Task Definition without deleting the old one, especially in case of rollback

## references
* https://github.com/hashicorp/terraform-provider-aws/releases/tag/v3.72.0
* https://github.com/hashicorp/terraform-provider-aws/pull/22269

### CODE REVIEW

**Review by korenyoni — CHANGES_REQUESTED** [review]
Thank you for the submission. Looks good, but:

* Tests are failing because the assertions were not updated in Terratest after the new attribute was added to example.
* `versions.tf` should be updated to require the minimum AWS provider version where this argent was added.

**Comment by cunymatthieu** [comment]
Ugh, I just realized that the parameter does not apply to the container definition, but to the Task Definition itself 😞 .
I cancel my PR.

**Comment by korenyoni** [comment]
@cunymatthieu Ah okay — didn't even notice that in my quick glance of a review. Thanks for the submission regardless.

**Pull request closed without merging**
